#!/bin/bash

set -euxo pipefail

# This script creates a custom bootable EFI binary by combining an EFI stub,
# Linux kernel, initrd, osrel and cmdline.

# Define variables
STUB=/usr/lib/systemd/boot/efi/linuxx64.efi.stub
KERNEL="${BINARIES_DIR}/bzImage"
# --- VERIFY THIS INITRD PATH ---
# Ensure this path correctly points to the CPIO archive you intend to use.
# Buildroot generates the CPIO in ${BINARIES_DIR}. Check if it's compressed
# (e.g., rootfs-sbnb.cpio.xz) or uncompressed (e.g., rootfs-sbnb.cpio)
# and adjust this variable and/or your Buildroot config accordingly.
# See notes in the defconfig section below.
INITRD="${BINARIES_DIR}/rootfs-sbnb.cpio"
OS_RELEASE="${TARGET_DIR}/etc/os-release"
# --- MODIFIED KERNEL COMMAND LINE ---
# Added 'nomodeset' to the end of the command line string.
# IMPORTANT: This command line is HARDCODED. Changes to BR2_KERNEL_CMDLINE_*
# in the Buildroot config will NOT affect the EFI file generated by this script.
CMDLINE="console=tty0 console=ttyS0 earlyprintk verbose intel_iommu=on module_blacklist=nouveau,nvidiafb,snd_hda_intel dyndbg=\"module firmware_class +p; module microcode +p; module ccp +p\" nomodeset"
# --- END MODIFICATION ---
CMDLINE_TMP=$(mktemp)
OUTPUT=sbnb.efi # Output filename in the current directory

# Write the command line to a temporary file
echo -n "${CMDLINE}" > "${CMDLINE_TMP}"

# Calculate alignment
align="$(objdump -p "${STUB}" | awk '{ if ($1 == "SectionAlignment"){print $2} }')"
align=$((16#$align))

# Calculate offsets for sections
stub_line=$(objdump -h "${STUB}" | tail -2 | head -1)
stub_size=0x$(echo "$stub_line" | awk '{print $3}')
stub_offs=0x$(echo "$stub_line" | awk '{print $4}')
osrel_offs=$((stub_size + stub_offs))
osrel_offs=$((osrel_offs + align - osrel_offs % align))
cmdline_offs=$((osrel_offs + $(stat -Lc%s "${OS_RELEASE}")))
cmdline_offs=$((cmdline_offs + align - cmdline_offs % align))
# --- NOTE: splash_offs Calculation ---
# The following offset is calculated but doesn't appear to be used in the
# objcopy command below in the original script. Verify if this is intended.
splash_offs=$((cmdline_offs + $(stat -Lc%s "${CMDLINE_TMP}")))
splash_offs=$((splash_offs + align - splash_offs % align))
# --- END NOTE ---
linux_offs=$((splash_offs)) # Original script sets linux_offs based on splash_offs
initrd_offs=$((linux_offs + $(stat -Lc%s "${KERNEL}")))
initrd_offs=$((initrd_offs + align - initrd_offs % align))

# Use objcopy to add sections to the EFI stub
# Ensure all required files exist before running objcopy
if [ ! -f "${OS_RELEASE}" ] || [ ! -f "${CMDLINE_TMP}" ] || [ ! -f "${KERNEL}" ] || [ ! -f "${INITRD}" ]; then
    echo "Error: One or more input files for objcopy not found!" >&2
    echo "OS_RELEASE: ${OS_RELEASE}" >&2
    echo "CMDLINE_TMP: ${CMDLINE_TMP}" >&2
    echo "KERNEL: ${KERNEL}" >&2
    echo "INITRD: ${INITRD}" >&2
    rm -f "${CMDLINE_TMP}" # Clean up temp file on error
    exit 1
fi

objcopy \
    --add-section .osrel="${OS_RELEASE}" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
    --add-section .cmdline="${CMDLINE_TMP}" --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
    --add-section .linux="${KERNEL}" --change-section-vma .linux=$(printf 0x%x $linux_offs) \
    --add-section .initrd="${INITRD}" --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
    "${STUB}" "${OUTPUT}"

# Clean up temporary file
rm -f "${CMDLINE_TMP}"

# Output the result
echo "Unified EFI executable created: ${OUTPUT}"

# Move the final EFI file to the standard Buildroot images directory
# BR2_ROOTFS_POST_IMAGE_SCRIPT runs from the Buildroot top-level directory.
# ${BINARIES_DIR} correctly points to output/images in this context.
mv "${OUTPUT}" "${BINARIES_DIR}/"
echo "Moved ${OUTPUT} to ${BINARIES_DIR}/"