---

- hosts: "{{ lookup('ansible.builtin.env', 'SBNB_HOSTS') }}"
  gather_facts: true
  ignore_unreachable: true

  tasks:
    - name: add docker apt key
      apt_key:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        state: present

    - name: add docker apt repo
      apt_repository:
        repo: "deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"
        state: present
        update_cache: yes

    - name: apt update
      apt:
        update_cache: yes

    - name: install nvidia-container-toolkit
      apt:
        pkg:
          - nvidia-container-toolkit
        state: present

    - name: Set docker runtime
      ansible.builtin.shell: |
        sudo nvidia-ctk runtime configure --runtime=docker

    - name: Restart docker service
      ansible.builtin.service:
        name: docker
        state: restarted
