---

- hosts: "{{ lookup('ansible.builtin.env', 'SBNB_HOSTS') }}"
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - name: Clone vllm src
      ansible.builtin.git:
        repo: 'https://github.com/vllm-project/vllm.git'
        version: 'v0.8.2'
        force: true
        dest: /mnt/sbnb-data/src/vllm

    - name: Install requirements
      community.docker.docker_container_exec:
        container: vllm
        command: >
          pip3 install -r /mnt/sbnb-data/src/vllm/requirements/test.txt

    - name: Run vllm benchmark
      community.docker.docker_container_exec:
        container: vllm
        command: >
          python3 /mnt/sbnb-data/src/vllm/benchmarks/benchmark_serving.py
            --backend openai
            --base-url http://127.0.0.1:8000
            --dataset-name=random
            --seed 12345
            --num-prompts=1000
            --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
      register: result

    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout
