---

- hosts: "{{ lookup('ansible.builtin.env', 'SBNB_HOSTS') }}"
  gather_facts: true
  ignore_unreachable: true

  tasks:
    - ping:

    - name: Start CPU stress test with sysbench 
      docker_container:
        name: sysbench
        image: perconalab/sysbench
        command: |
          /usr/bin/sysbench --time=600 --threads={{ ansible_facts['processor_nproc'] }} cpu run
